### ISSUE TITLE
difference 

### ISSUE THREAD

**Issue by az-z** [bitcraze/libdw1000#2]
Hello 
How is this project is different from arduino dw100 project by thotro?

**Comment by ataffanel** [comment]
Hi,
This project is originally based on the Arduino DW1000 lib.

This project is a C library that can be used in any system, embedded or not (for example this library is used in Crazyflie Loco Positioning System but could also easily be used in a RaspberryPi for example).

The Arduino DW1000 lib is written in C++ and is designed to be used in an Arduino environment.

If you are using Arduino, the Arduino lib is what you need. If you are using anything else you can consider using this lib.
/Arnaud

**Comment by az-z** [comment]
This is very interesting!
So I can run this on pic processors too?
How complete is the project - all api have been implemented ?

**Comment by ataffanel** [comment]
Yes it should work on a PIC (and if it doesn't please open a ticket ;-). All you have to do is to write a couple of hardware related functions: https://github.com/bitcraze/libdw1000#ops

The project is developed for the Loco positioning system. Using this lib we can implement Two Way Ranging, TDMA (with packet scheduling) and TDoA ranging is on the work. See https://github.com/bitcraze/lps-node-firmware. I have been adding function when I needed them (like scheduling packets). If there is something missing we can add it.

**Comment by az-z** [comment]
Arnaud,
This is truly wonderful. In all honesty I'm on arduino,  but my friends
have been urging me to shift to pic/anything more powerful than it.it is
quite possible that "I'll be back"@.
One last question- have you tried multiple anchors/multiple sensors
combination(s)? In my case I may have up to 100 tags per anchor at times.

**Comment by ataffanel** [comment]
Physically the radios can communicate with as many tag as you want, it is based on ieee802.15.4 standard. For the ranging algorithm what you are looking at then is TDoA algorithm. With two way ranging each tag will have to talk to the anchors and share the air. With TDoA the anchors are transmitting enough data in the air so that the tags only have to listen to get a position. For asset tracking you can also have the anchor listening and the tag sending a "ping" with some interval (but the anchor system needs to be synchronized then).

In our test we have run two way ranging to up to 4 tags (we can do more but it will limit the update rate too much for flying). We are currently working on TDoA.

Also the actual ranging algorithm are implemented in the lps-node-firmware and crazyflie-firmware projects. This lib only implements the DW1000 driver.
